'''Functions for mesh input/output, halfedge mesh processing with open3d, cutting a halfedge mesh along a curve, and Tutte embedding of a curved triangle to a flat equilateral triangle. '''

import open3d as o3d
import numpy as np
import trimesh
import igl
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
# Get vertices as numpy array
from scipy.spatial import cKDTree
from collections import deque
import re


import numpy as np

def write_polyline_to_obj(V=None, filename='polyline.obj'):
    """
    Write a polyline (loop) defined by vertices V to an OBJ file.
    
    Parameters
    ----------
    V : np.ndarray
        A (N, 3) array of vertices.
    filename : str, optional
        Output OBJ filename. Defaults to 'polyline.obj'.
    """
    if V is None:
        raise ValueError("You must provide a NumPy array of vertices.")
    if not isinstance(V, np.ndarray):
        raise TypeError("V must be a NumPy array.")
    if V.ndim != 2 or V.shape[1] != 3:
        raise ValueError("V must have shape (N, 3).")

    N = V.shape[0]
    
    with open(filename, 'w') as f:
        f.write("# OBJ file generated by write_polyline_to_obj\n")
        
        # Write vertices
        for v in V:
            f.write(f"v {v[0]} {v[1]} {v[2]}\n")
        
        # Write line elements: connect each vertex to the next, and last to first
        
        for i in range(1, N ):
            f.write("l ")
            f.write(f"{i} {i+1}\n")
        f.write(f"l {N} 1\n")  # closes the loop by connecting last to first

    print(f"Wrote polyline with {N} vertices to {filename}")

    



def parse_sharp_edges_from_obj(path):
    """
    Parses OBJ comments of the form:
    # Sharp Edges: (12,10)&(4,9)

    Returns:
        List of tuples: [(11, 9), (3, 8)]
    (it converts from 1-based to 0-based to fir with trimesh)
    """
    sharp_edges = []

    pattern = re.compile(
        r"#\s*Sharp\s+Edges\s*:\s*(.*)"
    )

    with open(path, "r") as f:
        for line in f:
            line = line.strip()

            match = pattern.match(line)
            if not match:
                continue

            payload = match.group(1)

            # Find all (a,b) pairs
            pairs = re.findall(r"\(\s*(\d+)\s*,\s*(\d+)\s*\)", payload)

            for a, b in pairs:
                sharp_edges.append((int(a)-1, int(b)-1))

    return sharp_edges



    
def normalise_to_unit_bbox(o3d_mesh):

    vertices = np.asarray(o3d_mesh.vertices)
    
    min_vals = np.min(vertices, axis=0)
    max_vals = np.max(vertices, axis=0)
    
    # Shift the vertices by subtracting the minimum values for each axis
    vertices = vertices - min_vals

    ranges = max_vals - min_vals
    scale = 1.0 / np.max(ranges)
    print(scale)
    
    # Scale the shifted vertices so that the largest extent in any axis is 0.5
    vertices = vertices * scale
    
    vertices = vertices - 0.5

    new_min_vals = np.min(vertices, axis=0)
    new_max_vals = np.max(vertices, axis=0)

    vertices = vertices - (new_min_vals+new_max_vals)/2

    # Update the mesh
    o3d_mesh.vertices = o3d.utility.Vector3dVector(vertices)
    o3d_mesh.compute_vertex_normals()
    
    return o3d_mesh

    

def he_mesh_from_file(mesh_filepath):
    mesh_o3d = o3d.io.read_triangle_mesh(mesh_filepath)
    mesh_o3d.compute_vertex_normals()
    he_mesh = o3d.geometry.HalfEdgeTriangleMesh.create_from_triangle_mesh(mesh_o3d)

    V_he = get_V_he(he_mesh)
    
    return he_mesh, V_he


def he_mesh_from_o3d(mesh_o3d):
    
    he_mesh = o3d.geometry.HalfEdgeTriangleMesh.create_from_triangle_mesh(mesh_o3d)
    V_he = get_V_he(he_mesh)
    
    return he_mesh, V_he

def o3d_mesh_from_file(mesh_filepath):
    
    mesh_o3d = o3d.io.read_triangle_mesh(mesh_filepath)
    return mesh_o3d


def o3d_mesh_from_he_mesh(he_mesh):
    mesh = o3d.geometry.TriangleMesh()
    mesh.vertices = o3d.utility.Vector3dVector(np.asarray(he_mesh.vertices))
    mesh.triangles = o3d.utility.Vector3iVector(np.asarray(he_mesh.triangles))
    return mesh
    

def get_V_he(he_mesh):

    print('Preparing V_he for halfedge mesh')

    V_he = [-1] * len(he_mesh.vertices)  # More efficient than list comprehension

    for i, he in enumerate(he_mesh.half_edges):
        if i % 10000 == 0 and i!=0:
            print(i, 'of', len(he_mesh.half_edges))
    
        V_he[he.vertex_indices[0]] = i  # Direct attribute access

    print('Prepared V_he for halfedge mesh.')
    print()

    return V_he



def optimise_V_he(he_mesh, V_he):
    """
    Assigns each vertex a boundary halfedge if the vertex is on a boundary.
    For interior vertices, keeps the original V_he.
    """

    he = he_mesh.half_edges
    print('Optimising V_he.')

    for i, he_id_0 in enumerate(V_he):
        he_id = he_id_0
        start_he = he_id_0
        found_boundary = False

        while True:
            if he[he_id].twin == -1:
                # this halfedge is a boundary, assign it to V_he
                V_he[i] = he_id
                found_boundary = True
                break

            # move to next halfedge around the vertex
            he_id = he[he[he_id].twin].next

            if he_id == start_he:
                # looped around, no boundary halfedge found
                break

        # Optional: if not found_boundary, V_he[i] remains unchanged

    print('Finished optimising V_he.\n')
    return V_he
